name: SignNick
version: ${project.version}
main: me.hsgamer.nick.Nick
authors:
  - HSGamer
api-version: 1.13
depend: [ProtocolLib]
softdepend: [Essentials]
description: NickName with sign-based editor

commands:
  nick:
    description: Change nick
  unnick:
    description: Reset nick
